extends Node
## RunState autoload — thin holder for the current run (godot-conventions.md
## autoload list). ALL progression logic lives in RunFlow (pure, tested); this node
## only keeps the live state dict and emits the EventBus run-lifecycle signals.
##
## In-run-only state (like Echoes) belongs here, NOT in the save — a run that ends
## is gone. The ONE sanctioned excursion to disk is the per-floor autosave
## checkpoint (PRD §7.13): to_checkpoint()/resume_from() snapshot and restore this
## node so a mid-run quit resumes at floor start — still within the same run, so
## nothing here ever outlives its run.

## The live RunFlow state dict; {} when not in a run.
var run: Dictionary = {}
## Which run this is (1-based, from the save's story counter) — for run_started.
var run_number: int = 0

# In-run-only state (PRD §7.5 — echoes die with the run, by design):
## Echo ids picked this run, in pick order (stackables may repeat).
var echoes: Array[String] = []
## How many echo offers were rolled (feeds the deterministic offer RNG).
var echo_offers_made: int = 0
## Player HP carried between rooms of the run; -1 = fresh (full).
var player_health: int = -1

# Door choice (design/run-structure.md) — NOT saved: the checkpoint resumes at floor
# start, where no incoming door exists, and the plan regenerates identically from the
# run seed. Math is DoorCore's; this node only holds the current floor's plan + the
# door the player walked to enter the CURRENT room.
## The current floor's door plan {floor, offers}; regenerated per floor.
var door_plan: Dictionary = {}
## The door {sigil, peril} that led INTO the current room; {} at floor start.
var pending_door: Dictionary = {}


func in_run() -> bool:
	return not run.is_empty() and not bool(run["over"])


func start_run(config: Dictionary, rng_seed: int, number: int) -> void:
	run = RunFlow.start(config, rng_seed)
	run_number = number
	echoes.clear()
	echo_offers_made = 0
	player_health = -1
	door_plan = {}
	pending_door = {}
	EventBus.run_started.emit(number)


func pick_echo(id: String) -> void:
	echoes.append(id)


## Snapshot for the per-floor autosave. Call as a floor's first room loads, so the
## stored run dict is already positioned at floor start.
func to_checkpoint() -> Dictionary:
	return {
		"run": run.duplicate(true),
		"run_number": run_number,
		"echoes": echoes.duplicate(),
		"player_health": player_health,
	}


## Restore a mid-run quit from its checkpoint (JSON round-trip: numbers come back
## as floats; RunFlow int()-casts everything it reads, we coerce the rest here).
func resume_from(checkpoint: Dictionary) -> void:
	run = (checkpoint.get("run", {}) as Dictionary).duplicate(true)
	# JSON round-trip / old checkpoints: coerce the rooms-cleared counter (2026-07-10;
	# missing on a pre-amendment checkpoint → 0, so its day tick just starts small).
	run["rooms_cleared"] = int(run.get("rooms_cleared", 0))
	run_number = int(checkpoint.get("run_number", 1))
	echoes.assign(checkpoint.get("echoes", []))
	echo_offers_made = echoes.size()  # offer RNG continues past the picks made so far
	player_health = int(checkpoint.get("player_health", -1))
	door_plan = {}       # regenerated by game.gd at the resumed floor's first room
	pending_door = {}    # a resume always lands at floor start — no incoming door
	EventBus.run_started.emit(run_number)


## Regenerate the current floor's door plan (game.gd calls this as a floor's first room
## loads — deterministic in the run seed, so a resume rebuilds the identical plan).
func build_floor_doors(weights: Dictionary, peril_chance: float) -> void:
	door_plan = DoorCore.generate_plan(
		int(run["seed"]), int(run["floor"]), int(run["rooms_this_floor"]), weights, peril_chance)


func room_kind() -> String:
	return RunFlow.room_kind(run)


## Current room cleared. Boss rooms also announce the kill (boss_id comes from the
## room scene — placeholder ids until real bosses land). Emits run_ended when the
## run finishes. Returns true if the run is still going (caller loads the next room).
func room_cleared(boss_id: String = "") -> bool:
	if not in_run():
		push_error("RunState.room_cleared() outside a run")
		return false
	if room_kind() == RunFlow.KIND_BOSS:
		EventBus.boss_killed.emit(boss_id, RunFlow.floor_reached(run))
	run = RunFlow.advance(run)
	if bool(run["over"]):
		_end_run()
		return false
	return true


## True when the CURRENT room is the run's LAST — the final floor's boss. The final
## chamber is handled specially (design 2026-07-07): after the boss valve, a codex artifact
## pedestal (the only way out) dissolves Tycho and ends the run. Call BEFORE room_cleared
## advances the run (game.gd checks it at the top of _on_room_cleared).
func is_final_boss() -> bool:
	return in_run() and room_kind() == RunFlow.KIND_BOSS \
		and int(run["floor"]) >= int(run["floors"])


## Final chamber: the boss just died. Announce the kill (counts toward boss_kills, feeds
## the boss valve) but DO NOT end the run — the player must still walk into the codex
## artifact. game.gd spawns the pedestal after the valve; finish_at_artifact() ends the
## run when it is entered. (This splits room_cleared's boss-emit from its run-end so the
## victory happens at the artifact, not at the kill.)
func final_boss_killed(boss_id: String = "") -> void:
	if not in_run():
		return
	EventBus.boss_killed.emit(boss_id, RunFlow.floor_reached(run))


## The player walked into the codex artifact (final chamber only) — end the run VICTORIOUS.
## Advances the still-open run to over+victory and emits run_ended with the SAME args a
## normal final-boss clear used to (game.gd's _on_run_ended does the day-tick/town tail).
## boss_killed already fired (final_boss_killed); the dissolve signal is emitted by the room.
func finish_at_artifact() -> void:
	if not in_run():
		return
	run = RunFlow.advance(run)  # final boss → over + victory
	_end_run()


## The player died in the current room (no penalty — locked design).
func player_died(source_id: String = "") -> void:
	if not in_run():
		return
	EventBus.death.emit(source_id)
	run = RunFlow.fail(run)
	_end_run()


## Abort the current run in memory WITHOUT emitting anything — no run_ended, no death, no
## boss_killed, so no day tick, no counters, no codex shard (design 2026-07-07). Used by the
## ESC menu's Forfeit ("like it never happened") and in-run Save & Quit. Clears the live run
## + all in-run state (echoes gone with it). The CALLER owns disk: forfeit restores the
## portal-entry snapshot and re-saves; in-run Save & Quit writes nothing (the floor-start
## checkpoint on disk IS the save). The next _start_run recomputes run_number, so an aborted
## run may leave an in-memory gap in the numbering — cosmetic only.
func abort_run() -> void:
	run = {}
	run_number = 0
	echoes.clear()
	echo_offers_made = 0
	player_health = -1
	door_plan = {}
	pending_door = {}


func _end_run() -> void:
	EventBus.run_ended.emit(
		bool(run["victory"]),
		RunFlow.floor_reached(run),
		{"rooms_this_floor": int(run["rooms_this_floor"]), "room": int(run["room"]),
			"rooms_cleared": int(run.get("rooms_cleared", 0))})  # feeds the room-scaled day tick
